### ISSUE TITLE
As a User, I can write data to Azure Blob Storage

### ISSUE THREAD

**Issue by bibimorlet** [artefactory/artefactory-connectors-kit#89]
WHY
In order to directly transfer raw data in Microsoft Azure Cloud.

HOW
Develop an Azure Blob writer in NCK

**Comment by louisRDSC** [comment]
Already existing storage writers (s3 and gcs) don't seem to have the same behavior :
- return values of write method
- handling of non-existing bucket

Shouldn't we normalize the behavior of storage writers before? as it has been done for the readers?

**Comment by benoitgoujon** [comment]
This is a good point. We need to keep the same behaviour across storage readers, you are right.

Can you describe what's the current state and what would be your target vision please 🙂  ?

**Comment by louisRDSC** [comment]
Currently S3_writter.write return an url to access the uploaded file (see doc https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html) and the bucket object while the gcs_writer.write return the uri of the uploaded file and the blob object. 
Moreover s3_writer create a bucket if the no bucket exist with the given bucket_name. gcs_writer will just throw an error (not sure about that) when trying to upload the file.

my target goal would be : 

-  remove the url from s3_writer for security issue and instead return the uri
-  remove the auto creation of a bucket if it doesn't exist (prevent creation of many buckets from typing errors, user should control bucket creation by himself)
- creation of a objectstorage_writer to factorize code as much as possible.
-  as I don't know why blob and bucket object are returned I would need help to choose the right behavior

What do you think about it?

**Comment by benoitgoujon** [comment]
Sounds good to me!

> remove the url from s3_writer for security issue and instead return the uri
Totally agree, this is much better and the presigned url does not work anyway, so go for the URI!

> remove the auto creation of a bucket if it doesn't exist
Also agree. But if the bucket does not exist, it would be great to return the list of buckets in the error message. Something like, "Did you mean bucketA? bucketB?" if the list is too long. Thus, if it is just a typo, it will make debugging easy.

>  creation of a objectstorage_writer to factorize code as much as possible
Yes if possible but there will be parts of the code we can't factorise like the authentication. So if it is too hard, don't waste your time on this 🙂
